- name: install Nginx
  hosts: WEB
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Start nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes

- name: Install Nginx
  hosts: WEB
  become: true
  roles:
    - sample